format = '''
$directory$git_branch$git_status$git_state $status
$character
'''

[directory]
style = 'bold green'
truncation_length = 8
truncation_symbol = '…/'
truncate_to_repo = false

[git_branch]
style = 'bold cyan'
format = '[$branch(:$remote_branch)]($style)'

[git_status]
format = '($all_status$ahead_behind)'
ahead = ' [⇡${count}](bold white)'
diverged = ' [⇕⇡${ahead_count}⇣]${behind_count}(bold white)'
behind = ' [⇣${count}](bold white)'
untracked = '[?](bold yellow)'
stashed = '[$](bold yellow)'
modified = '[!](bold yellow)'
staged = '[+](bold green)'

[character]
success_symbol = '[❯](#c88aff)'
error_symbol = '[✗](bold red) '
